import Link from "next/link";
import { notFound } from "next/navigation";
import { metadataFor } from "@/lib/seo";
import { portfolio, evidenceFor } from "@/lib/portfolio";
import { Intro } from "@/components/portfolio/Intro";
import { Ledger } from "@/components/portfolio/Ledger";
import { EvidenceFigure } from "@/components/portfolio/EvidenceFigure";
import { ExternalLink } from "@/components/portfolio/ExternalLink";
import { Faq } from "@/components/seo/Faq";
import { PageSchema } from "@/components/portfolio/PageSchema";
export const dynamicParams = false;
export function generateStaticParams() { return portfolio.projects.map(p => ({ slug: p.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; if (!portfolio.projects.some(p => p.slug === slug)) notFound(); return metadataFor(`/work/${slug}`); }
const related: Record<string, string[]> = { "edge-node": ["ghostcursor", "neuroux"], "cited-researcher": ["ledgerbridge", "studyos"], ledgerbridge: ["cited-researcher", "ghostcursor"], ghostcursor: ["edge-node", "ledgerbridge"], neuroux: ["edge-node", "cited-researcher"], studyos: ["cited-researcher", "neuroux"] };
export default async function CaseStudy({ params }: { params: Promise<{ slug: string }> }) {
 const { slug } = await params; const p = portfolio.projects.find(item => item.slug === slug); if (!p) notFound();
 const e = evidenceFor(slug), index = portfolio.projects.indexOf(p), previous = portfolio.projects[(index + portfolio.projects.length - 1) % portfolio.projects.length], next = portfolio.projects[(index + 1) % portfolio.projects.length];
 return <article className="case"><Intro title={`${p.title}: ${p.descriptor}`} work><p>{p.summary}</p></Intro><div className="case-grid"><aside className="case-rail"><dl><div className="rail-outcome"><dt>Outcome</dt><dd>{p.result}</dd></div><div><dt>Role</dt><dd>{p.role}</dd></div><div><dt>Dates</dt><dd>{p.year}</dd></div><div><dt>Stack</dt><dd>{p.stack.join(", ")}</dd></div><div><dt>Repository</dt><dd><ExternalLink href={p.repo}>{p.title} on GitHub</ExternalLink></dd></div><div><dt>Author</dt><dd><Link href="/about">{portfolio.name}</Link></dd></div></dl></aside><div className="case-body"><section id="problem"><h2>Problem</h2><p>{p.problem}</p></section><section id="approach"><h2>Approach</h2><ol className="approach-list">{p.approach.map(beat => <li key={beat}>{beat}</li>)}</ol></section><section id="result"><h2>Result</h2><p>{p.result}</p><Ledger id={`${slug}-ledger`} rows={e.metrics.map(metric => ({ metric, evidence: e }))} caption={slug === "studyos" ? "Table 1. No quantitative metrics were published for this project." : "Table 1. Reported results and their source caveats."} headline /><EvidenceFigure project={p} cited /></section><section id="limits"><h2>Limits and what comes next</h2><ul className="prose-list">{p.limits.map(limit => <li key={limit}>{limit}</li>)}</ul></section><section id="sources"><h2>Sources</h2><ol className="sources-list">{e.sources.map(s => <li id={`source-${s.id}`} key={s.id} data-cite={s.id}><span className="mark" data-cite={s.id}><ExternalLink href={s.url}>{s.title}</ExternalLink></span><Link href="#result" className="source-return">Back to result</Link></li>)}</ol></section><Faq route={`/work/${slug}`} /><section className="related-cases"><h2>Related case studies</h2>{related[slug].map(s => { const item = portfolio.projects.find(candidate => candidate.slug === s)!; return <div key={s}><h3><Link href={`/work/${s}`}>{item.title} case study</Link></h3><p className="caption">{item.descriptor}</p></div>; })}<nav className="case-ring" aria-label="Previous and next case studies"><Link href={`/work/${previous.slug}`}><span>Previous case</span>{previous.title}</Link><Link href={`/work/${next.slug}`}><span>Next case</span>{next.title}</Link></nav></section></div><aside className="case-sidenotes" aria-label="Evidence notes"><h2>Source notes</h2>{e.sources.map(s => <p key={s.id} data-cite={s.id}><a className="mark" data-cite={s.id} href={`#source-${s.id}`} aria-label={`Source ${s.id}: ${s.title}`}>[{s.id}]</a> {s.title}.<br /><span className="caption">Inspect the original report in Sources.</span></p>)}</aside></div><PageSchema route={`/work/${slug}`} /></article>;
}
